version: '2'
services:
  usercatalog-app:
    image: usercatalog
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://usercatalog-postgresql:5432/userCatalog
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://usercatalog-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://usercatalog-elasticsearch:9200
    ports:
      - 8080:8080
  usercatalog-postgresql:
    extends:
      file: postgresql.yml
      service: usercatalog-postgresql
  usercatalog-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: usercatalog-elasticsearch
